### ISSUE TITLE
Rank Editing?

### ISSUE THREAD

**Issue by Zardizzle** [Leanny/leanny.github.io#13] opened 2018-05-20 17:10 UTC
We can view our ranks, but we cannot edit them. I think this would be an easy one, as we can edit our salmon run ranks.

**Comment by Haxxie99** [comment] 2018-05-20 17:14
You can get banned in a second

**Comment by WemI0** [comment] 2018-05-20 17:20
Duplicate of #8

**Closed by WemI0** 2018-05-20 17:20 UTC
