### ISSUE TITLE
Consider splatoon3

### ISSUE THREAD

**Issue by 2819187400** [Leanny/leanny.github.io#160] opened 2022-09-13 08:13 UTC
Will you continue to update splatoon3 support?
Please update splathex
Let him support splatoon3

**Comment by Glazelf** [comment] 2022-09-13 08:30
Duplicate of #157

**Comment by 2819187400** [comment] 2022-09-13 12:49
There are already merchants in China who can modify it
But I don't know how

**Comment by Monotek18** [comment] 2022-09-23 17:31
Most likely scam, since the whole save data is downloaded from the servers when you boot the game

**Comment by Glazelf** [comment] 2022-09-23 18:07
> Most likely scam, since the whole save data is downloaded from the servers when you boot the game

They could be using Edizon cheat codes while having the game running, but it's a prime way to get banned either way and is not worth your time or money.

**Comment by Leanny** [comment] 2022-09-24 09:30
Yeah, the only way to achieve these modifications is memory editing, nothing we can achieve with savegame editing

**Closed by Leanny** 2022-09-24 09:30 UTC
